### ISSUE TITLE
Feat: Enhancing the UI of the team members cards at Team page

### ISSUE THREAD

**Issue by Asymtode712** [mdazfar2/ShellScript-Toolkit#465]
### Describe the feature

I want to enhance the UI of the team members cards at the `Team` page and also update their hovering effect

### Add ScreenShots

![Hover](https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/a16ad7ee-f433-4059-b69d-8d2d58f9c002)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@mdazfar2 please assign me this issue

**Comment by Asymtode712** [comment]
https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/7e6aaf91-6381-4e54-b377-adf3df70d3a3

@mdazfar2 please check whether this alternate effect is good for icons or should I keep the one which you specified in the discussion

**Comment by mdazfar2** [comment]
@Asymtode712 you have raised the sponsor icon

**Comment by mdazfar2** [comment]
@Asymtode712 The color of the effect must match the background card. According to the each special Card

**Comment by Asymtode712** [comment]
@mdazfar2 Will make the changes accordingly

**Comment by mdazfar2** [comment]
@Asymtode712 Hope you understand by looking at the screenshot below

<br>

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/235bf827-8350-47e4-b11f-b13b425a65e0)

**Comment by Asymtode712** [comment]
https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/46111d0f-f930-45c5-b5ce-f36a58ceca7c

@md@mdazfar2 Please check this

**Comment by mdazfar2** [comment]
@Asymtode712 incredible create pr
