### ISSUE TITLE
Feat: Backround  hue

### ISSUE THREAD

**Issue by happyrao78** [mdazfar2/ShellScript-Toolkit#490]
### Describe the feature

Adding the automatic background color changer which would increase the ui and user experience.

### Add ScreenShots

Something like this but it wont have start and stop buttons on reloading only the background color will start changing

https://github.com/mdazfar2/HelpOps-Hub/assets/138770813/103c7d05-19af-4d53-b981-14a19274dfac

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@happyrao78 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
