### ISSUE TITLE
Feat: Signing up user with email in database

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/ShellScript-Toolkit#717]
### Describe the feature

When attempting to sign up a new user with a valid email address, the system fails to create a new user account in the database. The following steps were taken to reproduce the issue:

### Steps to Reproduce
- Navigate to the sign-up page
- Enter a valid email address and password
- do Signin 
- Observe the system's response

### Expected 
The system should create a new user account in the database with the provided email address and password. The user should receive a confirmation email to verify their email address.

### Actual Result 
The system does not create a new user account in the database. The user is not redirected to a success page or sent a confirmation email. Instead, the system displays an error message (if any) or remains on the sign-up page

### Demo Screenrecord

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/e3a76228-1a9e-4cea-9eaf-c627e12a3eac

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 assigned
