### ISSUE TITLE
Feat: Want to add the share button so that user can share their profile to anyone and also want to show the same link in the browsers url 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [mdazfar2/ShellScript-Toolkit#986]
### Describe the feature

I want to give the facility to the user of sharing their profiles when they want  by clicking just a single button 
I also want to show that id to the url  Person can also copy that directly from their 

### Add ScreenShots

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/531b3762-59d1-48ed-af3e-c31bc1e049d8)
![image](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/1280ee19-5340-401e-8cf7-164129ca4fcf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 you are assigned.
